{
 "title": "Defluencer Testground",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Video Stops",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "video",
     "select": [
      [
       { "params": [ "stop" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Video Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "video",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Video Skips",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "video",
     "select": [
      [
       { "params": [ "skip" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Video Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "video",
     "select": [
      [
       { "params": [ "buffer" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Video Segment Fetch",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "video",
     "select": [
      [
       { "params": [ "fetch" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Video Gossips Buffer",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "video",
     "select": [
      [
       { "params": [ "gossips" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Jitter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GossipSub Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "gossips",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GossipSub Jitter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sim_id" ], "type": "tag" }
     ],
     "measurement": "gossips",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}