[package]
name = "live_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.21.4", default-features = false, features = ["aio", "tokio-comp"] }
structopt = { version = "0.3", default-features = false, features = [] }
tokio = { version = "1", default-features = false, features = ["macros", "rt", "time"] }