name = "streaming_test"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[builders."docker:go"]
enabled = false

[builders."exec:go"]
enabled = false

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = false

[runners."cluster:k8s"]
enabled = false

[[testcases]]
name= "quickstart"
instances = { min = 12, max = 400, default = 40 }

  [testcases.params]
  log = { type = "bool", default = "true" }
  log_id = { type = "int", default = 40 }
  network_bandwidth = { type = "int", default = 10000000 }
  max_concurrent_send = { type = "int", default = 4 }
  max_size_block = { type = "bool", default = "false" }
  segment_length = { type = "int", default = 4 }
  sim_time = { type = "int", default = 300 }
  video_bitrate = { type = "int", default = 6000000 }
